### ISSUE TITLE
a tiny little example required

### ISSUE THREAD

**Issue by parweb** [skerit/peerpin#1]
The name and small description seems promising maybe a simple working example would be great ?

**Comment by skerit** [comment]
@parweb Done! I added a basic example at `test/example.js` you can run on 2 different computers and see if it works, like so:

```
node test/example.js my-cool-network-name
```

And then just hope the hole punching works :)

**Comment by skerit** [comment]
@parweb Closing the issue for now, if you have any more questions, feel free to reopen or create a new issue.
